development:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
test:
  access_key_id: abc...
  secret_access_key: abc...
production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
