# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03475c41fff721ffd64f8831b3010fdcec47b6103aed99efd9e743e7576974c18da166d1d8a7d365ec7fcc81374661121852867d5e56986181fe631dba64fbf8

test:
  secret_key_base: c6c49e3b1e8564813867dad6a6e9031cbf3f826f01abf581de8e01ee5bd2ed10b1543a9f4fdf5e552a0f4967805250e332934bdf84bab56c3699aac2a52053af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
